#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config/serverfiles/

# Update or install
if [[ "$(cat /config/serverfiles/lsts3version)" != "${TS3_VERSION}" ]]; then
  echo "Updating or Installing Teamspeak3 at ${TS3_VERSION}"
  curl -s http://dl.4players.de/ts/releases/${TS3_VERSION}/teamspeak3-server_linux_amd64-${TS3_VERSION}.tar.bz2 | \
  tar xfj - --strip-components=1 -C /config/serverfiles/
fi

# Grab default config if no file exists
if [ ! -e /config/serverfiles/ts3-server.ini ]; then
  wget https://raw.githubusercontent.com/GameServerManagers/Game-Server-Configs/master/TeamSpeak3/ts3server.ini -O /config/serverfiles/ts3-server.ini
  chmod 440 /config/serverfiles/ts3-server.ini
fi

# Tag current version
echo ${TS3_VERSION} > /config/serverfiles/lsts3version

# permissions
chown abc:abc -R /config
